# Generated by Django 5.1.6 on 2026-05-19 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('inventory', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesatransaction',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_transactions', to='sales.sale'),
        ),
        migrations.AddField(
            model_name='mpesacallbacklog',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='callback_logs', to='finance.mpesatransaction'),
        ),
        migrations.AddField(
            model_name='profitaccount',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profit_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profittransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profittransaction',
            name='profit_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.profitaccount'),
        ),
        migrations.AddField(
            model_name='purchaseaccount',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchasetransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchasetransaction',
            name='purchase_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.purchaseaccount'),
        ),
        migrations.AddField(
            model_name='salary',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salaries_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salary',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salaries_paid', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salary',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='salary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_transactions', to='finance.salary'),
        ),
        migrations.AddField(
            model_name='stockpurchase',
            name='account_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_purchases', to='finance.accounttransaction'),
        ),
        migrations.AddField(
            model_name='stockpurchase',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockpurchase',
            name='financial_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_purchases', to='finance.financialtransaction'),
        ),
        migrations.AddField(
            model_name='stockpurchase',
            name='stock_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_transactions', to='inventory.stockentry'),
        ),
        migrations.AddIndex(
            model_name='accounttransaction',
            index=models.Index(fields=['account_type'], name='finance_acc_account_2bb1d1_idx'),
        ),
        migrations.AddIndex(
            model_name='accounttransaction',
            index=models.Index(fields=['-transaction_date'], name='finance_acc_transac_f3168b_idx'),
        ),
        migrations.AddIndex(
            model_name='capitalinjection',
            index=models.Index(fields=['source_type'], name='finance_cap_source__b26e1c_idx'),
        ),
        migrations.AddIndex(
            model_name='capitalinjection',
            index=models.Index(fields=['status'], name='finance_cap_status_72cf0c_idx'),
        ),
        migrations.AddIndex(
            model_name='capitalinjection',
            index=models.Index(fields=['-transaction_date'], name='finance_cap_transac_b48d82_idx'),
        ),
        migrations.AddIndex(
            model_name='incometransaction',
            index=models.Index(fields=['-transaction_date'], name='finance_inc_transac_42d45d_idx'),
        ),
        migrations.AddIndex(
            model_name='incometransaction',
            index=models.Index(fields=['transaction_type'], name='finance_inc_transac_240f5e_idx'),
        ),
        migrations.AddIndex(
            model_name='moneytransfer',
            index=models.Index(fields=['from_account', 'to_account'], name='finance_mon_from_ac_76d2b0_idx'),
        ),
        migrations.AddIndex(
            model_name='moneytransfer',
            index=models.Index(fields=['status'], name='finance_mon_status_7c7536_idx'),
        ),
        migrations.AddIndex(
            model_name='moneytransfer',
            index=models.Index(fields=['transfer_reference'], name='finance_mon_transfe_868714_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesatransaction',
            index=models.Index(fields=['merchant_request_id'], name='finance_mpe_merchan_95e2d9_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesatransaction',
            index=models.Index(fields=['checkout_request_id'], name='finance_mpe_checkou_d417ae_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesatransaction',
            index=models.Index(fields=['mpesa_receipt_number'], name='finance_mpe_mpesa_r_9c58b0_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesatransaction',
            index=models.Index(fields=['status', 'created_at'], name='finance_mpe_status_1a3d58_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesatransaction',
            index=models.Index(fields=['phone_number', 'status'], name='finance_mpe_phone_n_2c7033_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesacallbacklog',
            index=models.Index(fields=['checkout_request_id'], name='finance_mpe_checkou_021ba7_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesacallbacklog',
            index=models.Index(fields=['-created_at'], name='finance_mpe_created_e65cf6_idx'),
        ),
        migrations.AddIndex(
            model_name='profittransaction',
            index=models.Index(fields=['-transaction_date'], name='finance_pro_transac_98a149_idx'),
        ),
        migrations.AddIndex(
            model_name='profittransaction',
            index=models.Index(fields=['transaction_type'], name='finance_pro_transac_9ee557_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasetransaction',
            index=models.Index(fields=['-transaction_date'], name='finance_pur_transac_468c9b_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasetransaction',
            index=models.Index(fields=['transaction_type'], name='finance_pur_transac_e80b1a_idx'),
        ),
        migrations.AddIndex(
            model_name='salary',
            index=models.Index(fields=['staff', 'status'], name='finance_sal_staff_i_7447fb_idx'),
        ),
        migrations.AddIndex(
            model_name='salary',
            index=models.Index(fields=['status'], name='finance_sal_status_f79dcb_idx'),
        ),
        migrations.AddIndex(
            model_name='salary',
            index=models.Index(fields=['-year', '-month'], name='finance_sal_year_d432e2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='salary',
            unique_together={('staff', 'month', 'year')},
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['transaction_type'], name='finance_fin_transac_ef0571_idx'),
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['-transaction_date'], name='finance_fin_transac_6cad6f_idx'),
        ),
        migrations.AddIndex(
            model_name='stockpurchase',
            index=models.Index(fields=['sku_code'], name='finance_sto_sku_cod_9684a2_idx'),
        ),
        migrations.AddIndex(
            model_name='stockpurchase',
            index=models.Index(fields=['-purchase_date'], name='finance_sto_purchas_ea1038_idx'),
        ),
    ]
