# Generated by Django 6.0.2 on 2026-04-18 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_mpesatransaction_mpesacallbacklog_and_more'),
        ('sales', '0004_salereversal_sales_saler_reverse_4c9072_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mpesatransaction',
            name='credit_payment',
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_transactions', to='sales.sale'),
        ),
    ]
