# Generated by Django 5.1.6 on 2026-05-20 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_injectionaccount_injectiontransaction_netaccount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='injectionaccount',
            old_name='balance',
            new_name='total_injected_all_time',
        ),
        migrations.RemoveField(
            model_name='injectionaccount',
            name='total_transferred_to_net',
        ),
    ]
