# Generated by Django 5.1.6 on 2026-05-22 14:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_rename_balance_injectionaccount_total_injected_all_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsaccount',
            name='total_profits_taken',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='savingstransaction',
            name='transaction_type',
            field=models.CharField(choices=[('profit', 'Profit Added'), ('transfer_out', 'Transfer to Injection'), ('profit_taken', 'Profit Taken by Owner')], max_length=20),
        ),
    ]
