# Generated by Django 5.1.6 on 2026-05-22 20:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_savingsaccount_total_profits_taken_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='financialtransaction',
            unique_together={('transaction_type', 'amount', 'description', 'transaction_date')},
        ),
        migrations.AlterUniqueTogether(
            name='nettransaction',
            unique_together={('category', 'amount', 'description', 'transaction_date')},
        ),
        migrations.AlterUniqueTogether(
            name='savingstransaction',
            unique_together={('transaction_type', 'amount', 'sale_reference')},
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['transaction_type', 'amount', 'transaction_date'], name='finance_fin_transac_6d0393_idx'),
        ),
        migrations.AddIndex(
            model_name='nettransaction',
            index=models.Index(fields=['category', 'amount', 'transaction_date'], name='finance_net_categor_5c41d3_idx'),
        ),
    ]
