# Generated by Django 5.1.6 on 2026-05-23 12:28

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_financialtransaction_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_purchased', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_cogs', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inventory Asset',
                'verbose_name_plural': 'Inventory Assets',
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transaction_type', models.CharField(choices=[('purchase', 'Stock Purchase (Asset Increase)'), ('cogs', 'Cost of Goods Sold (Asset Decrease)'), ('adjustment_increase', 'Manual Increase'), ('adjustment_decrease', 'Manual Decrease')], max_length=20)),
                ('sku_code', models.CharField(blank=True, db_index=True, max_length=50)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('sale_reference', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('inventory_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.inventoryasset')),
            ],
            options={
                'ordering': ['-transaction_date'],
                'indexes': [models.Index(fields=['-transaction_date'], name='finance_inv_transac_a13937_idx'), models.Index(fields=['transaction_type'], name='finance_inv_transac_bde7b5_idx'), models.Index(fields=['sku_code'], name='finance_inv_sku_cod_1180a1_idx')],
            },
        ),
    ]
