# Generated by Django 5.1.6 on 2026-05-25 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_inventoryasset_inventorytransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingstransaction',
            name='transaction_type',
            field=models.CharField(choices=[('profit', 'Profit Added'), ('transfer_out', 'Transfer to Injection'), ('profit_taken', 'Profit Taken by Owner'), ('expense', 'Expense Deduction')], max_length=20),
        ),
    ]
