# Generated by Django 5.1.6 on 2026-06-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_alter_savingstransaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingstransaction',
            name='transaction_type',
            field=models.CharField(choices=[('profit', 'Profit Added'), ('transfer_out', 'Transfer to Injection'), ('transfer_to_injection', 'Transfer to Injection Account'), ('profit_taken', 'Profit Taken by Owner'), ('expense', 'Expense Deduction')], max_length=30),
        ),
    ]
