# Generated by Django 5.1.6 on 2026-05-19 17:00

import django.db.models.deletion
import django.utils.timezone
import staff.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('purpose', models.CharField(default='dashboard_access', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=20, unique=True)),
                ('id_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('position', models.CharField(choices=[('administrator', 'Administrator'), ('assistant_manager', 'Assistant Manager'), ('sales_manager', 'Sales Manager'), ('sales_agent', 'Sales Agent'), ('cashier', 'Cashier'), ('store_manager', 'Store Manager'), ('credit_manager', 'Credit Manager'), ('credit_officer', 'Credit Officer'), ('customer_service', 'Customer Service'), ('finance_manager', 'Finance Manager'), ('security', 'Security Officer'), ('cleaner', 'Cleaner'), ('inventory_manager', 'Inventory Manager'), ('mpesa_agent', 'M-Pesa Agent'), ('technician', 'Technician')], max_length=50)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('verification_code', models.CharField(blank=True, max_length=10, null=True)),
                ('verification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('verification_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_attempts', models.IntegerField(default=0)),
                ('is_identity_verified', models.BooleanField(default=False)),
                ('verification_notes', models.TextField(blank=True)),
                ('id_front', models.ImageField(blank=True, max_length=500, null=True, upload_to='verification/ids/')),
                ('id_back', models.ImageField(blank=True, max_length=500, null=True, upload_to='verification/ids/')),
                ('passport_photo', models.ImageField(blank=True, max_length=500, null=True, upload_to='verification/photos/')),
                ('live_photo', models.ImageField(blank=True, max_length=500, null=True, upload_to='verification/live/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_shop', models.ForeignKey(blank=True, help_text='Shop branch assigned to this staff member', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_staff', to='shops.shopbranch')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_staff', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Member',
                'verbose_name_plural': 'Staff Members',
            },
        ),
        migrations.CreateModel(
            name='StaffApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('id_number', models.CharField(max_length=50, unique=True)),
                ('address', models.TextField(blank=True)),
                ('position', models.CharField(choices=[('administrator', 'Administrator'), ('assistant_manager', 'Assistant Manager'), ('sales_manager', 'Sales Manager'), ('sales_agent', 'Sales Agent'), ('cashier', 'Cashier'), ('store_manager', 'Store Manager'), ('credit_manager', 'Credit Manager'), ('credit_officer', 'Credit Officer'), ('customer_service', 'Customer Service'), ('finance_manager', 'Finance Manager'), ('security', 'Security Officer'), ('cleaner', 'Cleaner'), ('inventory_manager', 'Inventory Manager'), ('mpesa_agent', 'M-Pesa Agent'), ('technician', 'Technician')], max_length=50)),
                ('experience', models.TextField(blank=True)),
                ('passport_photo', models.ImageField(max_length=500, upload_to=staff.models.passport_upload_path)),
                ('id_front', models.ImageField(max_length=500, upload_to=staff.models.id_front_upload_path)),
                ('id_back', models.ImageField(max_length=500, upload_to=staff.models.id_back_upload_path)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('under_review', 'Under Review')], default='pending', max_length=20)),
                ('application_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, help_text='Notes from the review process', null=True)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('privacy_accepted', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_user', models.ForeignKey(blank=True, help_text='User account created when application was approved', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_applications', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Application',
                'verbose_name_plural': 'Staff Applications',
                'ordering': ['-application_date'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_changed', models.BooleanField(default=False)),
                ('first_login', models.BooleanField(default=True)),
                ('last_password_change', models.DateTimeField(blank=True, null=True)),
                ('is_ceo', models.BooleanField(default=False, help_text='CEO/Company Owner status')),
                ('is_verified', models.BooleanField(default=False, help_text='User identity verified')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('lock_reason', models.CharField(blank=True, choices=[('failed_login', 'Multiple Failed Logins'), ('suspicious', 'Suspicious Activity'), ('admin', 'Admin Lock')], max_length=50)),
                ('failed_login_attempts', models.IntegerField(default=0)),
                ('last_failed_login', models.DateTimeField(blank=True, null=True)),
                ('is_suspended', models.BooleanField(default=False)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('suspended_until', models.DateTimeField(blank=True, null=True)),
                ('suspension_reason', models.TextField(blank=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivated_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deactivated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deactivated_users', to=settings.AUTH_USER_MODEL)),
                ('suspended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspended_users', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Status',
                'verbose_name_plural': 'User Statuses',
                'indexes': [models.Index(fields=['is_locked', 'is_suspended'], name='staff_users_is_lock_6cf532_idx'), models.Index(fields=['user', 'is_locked'], name='staff_users_user_id_6c6734_idx')],
            },
        ),
    ]
