# Generated by Django 6.0.2 on 2026-02-18 19:52

import django.db.models.deletion
import django.utils.timezone
import staff.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('id_number', models.CharField(max_length=50, unique=True)),
                ('address', models.TextField(blank=True)),
                ('position', models.CharField(choices=[('sales_assistant', 'Sales Officer'), ('cashier', 'Cashier Desk'), ('store_manager', 'Store Manager'), ('inventory_clerk', 'Inventory Clerk'), ('customer_service', 'Customer Care Service'), ('supervisor', 'Supervisor'), ('assistant_manager', 'Sales Manager'), ('security', 'Security Officer'), ('cleaner', 'Office Cleaner')], max_length=50)),
                ('experience', models.TextField(blank=True)),
                ('passport_photo', models.ImageField(upload_to=staff.models.passport_upload_path)),
                ('id_front', models.ImageField(upload_to=staff.models.id_front_upload_path)),
                ('id_back', models.ImageField(upload_to=staff.models.id_back_upload_path)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('under_review', 'Under Review')], default='pending', max_length=20)),
                ('application_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('privacy_accepted', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_applications', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Application',
                'verbose_name_plural': 'Staff Applications',
                'ordering': ['-application_date'],
            },
        ),
    ]
