# Generated by Django 6.0.2 on 2026-02-19 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffapplication',
            name='created_user',
            field=models.ForeignKey(blank=True, help_text='User account created when application was approved', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='staffapplication',
            name='review_notes',
            field=models.TextField(blank=True, help_text='Notes from the review process', null=True),
        ),
    ]
