# Generated by Django 5.1.6 on 2026-05-24 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['staff_id'], 'verbose_name': 'Staff Member', 'verbose_name_plural': 'Staff Members'},
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='ApplicationExtraData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resident', models.TextField(blank=True, help_text='Current residence address')),
                ('former_employer', models.CharField(blank=True, max_length=200)),
                ('preferred_salary', models.CharField(blank=True, max_length=50)),
                ('signature', models.TextField(blank=True, help_text='Digital signature')),
                ('other_documents', models.FileField(blank=True, help_text='Additional supporting documents (CV, certificates, etc.)', null=True, upload_to='staff_documents/other/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extra_data', to='staff.staffapplication')),
            ],
        ),
    ]
