# Generated by Django 6.0.2 on 2026-02-21 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_staffapplication_created_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffapplication',
            name='position',
            field=models.CharField(choices=[('sales_agent', 'Sales Officer'), ('cashier', 'Cashier Desk'), ('store_manager', 'Store Manager'), ('sales_manager', 'Sales Manager'), ('credit_manager', 'Credit Manager'), ('customer_service', 'Customer Care Service'), ('supervisor', 'Supervisor'), ('security', 'Security Officer'), ('cleaner', 'Office Cleaner')], max_length=50),
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('purpose', models.CharField(default='dashboard_access', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
