# Generated by Django 6.0.2 on 2026-02-28 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffapplication',
            name='position',
            field=models.CharField(choices=[('administrator', 'Administrator'), ('sales_manager', 'Sales Manager'), ('sales_agent', 'Sales Agent'), ('cashier', 'Cashier'), ('store_manager', 'Store Manager'), ('credit_manager', 'Credit Manager'), ('credit_officer', 'Credit Officer'), ('customer_service', 'Customer Service'), ('supervisor', 'Supervisor'), ('security', 'Security Officer'), ('cleaner', 'Cleaner'), ('inventory_manager', 'Inventory Manager')], max_length=50),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=20, unique=True)),
                ('position', models.CharField(choices=[('administrator', 'Administrator'), ('sales_manager', 'Sales Manager'), ('sales_agent', 'Sales Agent'), ('cashier', 'Cashier'), ('store_manager', 'Store Manager'), ('credit_manager', 'Credit Manager'), ('credit_officer', 'Credit Officer'), ('customer_service', 'Customer Service'), ('supervisor', 'Supervisor'), ('security', 'Security Officer'), ('cleaner', 'Cleaner'), ('inventory_manager', 'Inventory Manager')], max_length=50)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('verification_code', models.CharField(blank=True, max_length=10, null=True)),
                ('verification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('verification_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_attempts', models.IntegerField(default=0)),
                ('is_identity_verified', models.BooleanField(default=False)),
                ('verification_notes', models.TextField(blank=True)),
                ('id_front', models.ImageField(blank=True, null=True, upload_to='verification/ids/')),
                ('id_back', models.ImageField(blank=True, null=True, upload_to='verification/ids/')),
                ('passport_photo', models.ImageField(blank=True, null=True, upload_to='verification/photos/')),
                ('live_photo', models.ImageField(blank=True, null=True, upload_to='verification/live/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_staff', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Member',
                'verbose_name_plural': 'Staff Members',
            },
        ),
    ]
