# Generated by Django 6.0.2 on 2026-03-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_alter_staffapplication_position_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='position',
            field=models.CharField(choices=[('administrator', 'Administrator'), ('sales_manager', 'Sales Manager'), ('sales_agent', 'Sales Agent'), ('cashier', 'Cashier'), ('store_manager', 'Store Manager'), ('credit_manager', 'Credit Manager'), ('credit_officer', 'Credit Officer'), ('customer_service', 'Customer Service'), ('finance', 'finance'), ('security', 'Security Officer'), ('cleaner', 'Cleaner'), ('inventory_manager', 'Inventory Manager')], max_length=50),
        ),
        migrations.AlterField(
            model_name='staffapplication',
            name='position',
            field=models.CharField(choices=[('administrator', 'Administrator'), ('sales_manager', 'Sales Manager'), ('sales_agent', 'Sales Agent'), ('cashier', 'Cashier'), ('store_manager', 'Store Manager'), ('credit_manager', 'Credit Manager'), ('credit_officer', 'Credit Officer'), ('customer_service', 'Customer Service'), ('finance', 'finance'), ('security', 'Security Officer'), ('cleaner', 'Cleaner'), ('inventory_manager', 'Inventory Manager')], max_length=50),
        ),
    ]
