# Generated by Django 6.0.2 on 2026-03-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_alter_staff_position_alter_staffapplication_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='id_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
