# Generated by Django 6.0.2 on 2026-03-31 07:23

import staff.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0010_increase_image_field_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffapplication',
            name='id_back',
            field=models.ImageField(max_length=500, upload_to=staff.models.id_back_upload_path),
        ),
        migrations.AlterField(
            model_name='staffapplication',
            name='id_front',
            field=models.ImageField(max_length=500, upload_to=staff.models.id_front_upload_path),
        ),
        migrations.AlterField(
            model_name='staffapplication',
            name='passport_photo',
            field=models.ImageField(max_length=500, upload_to=staff.models.passport_upload_path),
        ),
    ]
