# Generated by Django 6.0.2 on 2026-04-09 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
        ('staff', '0011_alter_staffapplication_id_back_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='assigned_shop',
            field=models.ForeignKey(blank=True, help_text='Shop branch assigned to this staff member', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_staff', to='shops.shopbranch'),
        ),
    ]
