# Generated by Django 6.0.2 on 2026-04-28 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_staff_assigned_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='position',
            field=models.CharField(choices=[('administrator', 'Administrator'), ('assistant_manager', 'Assistant Manager'), ('sales_manager', 'Sales Manager'), ('sales_agent', 'Sales Agent'), ('cashier', 'Cashier'), ('store_manager', 'Store Manager'), ('credit_manager', 'Credit Manager'), ('credit_officer', 'Credit Officer'), ('customer_service', 'Customer Service'), ('finance_manager', 'Finance Manager'), ('security', 'Security Officer'), ('cleaner', 'Cleaner'), ('inventory_manager', 'Inventory Manager'), ('mpesa_agent', 'M-Pesa Agent')], max_length=50),
        ),
        migrations.AlterField(
            model_name='staffapplication',
            name='position',
            field=models.CharField(choices=[('administrator', 'Administrator'), ('assistant_manager', 'Assistant Manager'), ('sales_manager', 'Sales Manager'), ('sales_agent', 'Sales Agent'), ('cashier', 'Cashier'), ('store_manager', 'Store Manager'), ('credit_manager', 'Credit Manager'), ('credit_officer', 'Credit Officer'), ('customer_service', 'Customer Service'), ('finance_manager', 'Finance Manager'), ('security', 'Security Officer'), ('cleaner', 'Cleaner'), ('inventory_manager', 'Inventory Manager'), ('mpesa_agent', 'M-Pesa Agent')], max_length=50),
        ),
    ]
