# Generated by Django 6.0.2 on 2026-05-19 15:11

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditTransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Transaction Created'), ('paid', 'Paid by Company'), ('cancelled', 'Cancelled'), ('reversed', 'Reversed'), ('updated', 'Updated'), ('commission_paid', 'Commission Paid to Seller'), ('commission_cancelled', 'Commission Cancelled')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SellerCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Commission amount earned', max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('mpesa', 'M-Pesa')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SellerCommissionSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_earned', models.DecimalField(decimal_places=2, default=0, help_text='Total commissions earned (including paid and pending)', max_digits=12)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, help_text='Total commissions paid out', max_digits=12)),
                ('total_pending', models.DecimalField(decimal_places=2, default=0, help_text='Total commissions pending payment', max_digits=12)),
                ('last_paid_date', models.DateTimeField(blank=True, null=True)),
                ('last_paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transactions_count', models.IntegerField(default=0)),
                ('paid_transactions_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Seller Commission Summary',
                'verbose_name_plural': 'Seller Commission Summaries',
            },
        ),
        migrations.CreateModel(
            name='CreditCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('email', models.EmailField(help_text='Company email for communication', max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('contact_person', models.CharField(blank=True, max_length=200)),
                ('code', models.CharField(blank=True, help_text='Auto-generated if left blank', max_length=50, unique=True)),
                ('address', models.TextField(blank=True)),
                ('payment_terms', models.CharField(blank=True, help_text='e.g., Net 30, Net 45, Weekly on Friday', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credit Company',
                'verbose_name_plural': 'Credit Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total amount paid', max_digits=12)),
                ('payment_method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('bank', 'Bank Transfer'), ('cheque', 'Cheque'), ('cash', 'Cash')], max_length=20)),
                ('payment_reference', models.CharField(help_text='M-Pesa code, bank reference, cheque number, etc.', max_length=200)),
                ('payment_date', models.DateField()),
                ('bank_name', models.CharField(blank=True, max_length=200)),
                ('account_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to=settings.AUTH_USER_MODEL)),
                ('credit_company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='credit.creditcompany')),
            ],
            options={
                'verbose_name': 'Company Payment',
                'verbose_name_plural': 'Company Payments',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='CreditCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('id_number', models.CharField(max_length=50, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('alternate_phone', models.CharField(blank=True, max_length=20)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('town', models.CharField(blank=True, max_length=100)),
                ('physical_address', models.TextField(blank=True)),
                ('nok_name', models.CharField(blank=True, max_length=200)),
                ('nok_phone', models.CharField(blank=True, max_length=20)),
                ('passport_photo', models.ImageField(blank=True, help_text="Customer's passport photo", null=True, upload_to='customers/passports/')),
                ('id_front_photo', models.ImageField(blank=True, help_text='Front side of national ID', null=True, upload_to='customers/id_front/')),
                ('id_back_photo', models.ImageField(blank=True, help_text='Back side of national ID', null=True, upload_to='customers/id_back/')),
                ('additional_document', models.FileField(blank=True, help_text='Any additional supporting document', null=True, upload_to='customers/documents/')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(db_index=True, help_text='Auto-generated transaction ID in format #SALE-XXXX', max_length=100, unique=True)),
                ('product_name', models.CharField(blank=True, help_text='Product name at time of sale', max_length=200)),
                ('product_code', models.CharField(blank=True, help_text='Product code at time of sale', max_length=100)),
                ('imei', models.CharField(blank=True, help_text='Phone IMEI number (if applicable)', max_length=100)),
                ('ceiling_price', models.DecimalField(decimal_places=2, help_text='Amount the credit company will pay you', max_digits=12)),
                ('partial_payment_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount already paid for partial payments (when company pays partially)', max_digits=12)),
                ('commission_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', help_text='How commission is calculated', max_length=20)),
                ('commission_value', models.DecimalField(decimal_places=2, default=0, help_text='Percentage (e.g., 5 for 5%) or fixed amount in KSH', max_digits=10)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, help_text='Calculated commission amount (auto-filled)', max_digits=12)),
                ('commission_status', models.CharField(choices=[('not_set', 'Not Set'), ('requested', 'Requested'), ('approved', 'Approved'), ('paid', 'Paid to Seller'), ('cancelled', 'Cancelled')], default='not_set', help_text="Status of seller's commission", max_length=20)),
                ('commission_paid_date', models.DateTimeField(blank=True, help_text='When commission was paid to seller', null=True)),
                ('commission_notes', models.TextField(blank=True, help_text='Notes about commission payment')),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When the credit transaction was created')),
                ('paid_date', models.DateTimeField(blank=True, help_text='When the company fully paid you', null=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending Payment'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid by Company'), ('cancelled', 'Cancelled'), ('reversed', 'Reversed')], default='pending', help_text='Payment status from the credit company', max_length=20)),
                ('payment_reference', models.CharField(blank=True, help_text="Company's payment reference (M-Pesa code, bank ref, etc.)", max_length=200)),
                ('etr_receipt_number', models.CharField(blank=True, help_text='ETR receipt number (e.g., 0501)', max_length=50, null=True)),
                ('company_reference', models.CharField(blank=True, help_text='Reference number from the credit company', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('reversal_reason', models.TextField(blank=True)),
                ('finance_transaction_id', models.CharField(blank=True, help_text='Link to FinancialTransaction in finance app', max_length=100, null=True)),
                ('finance_account_type', models.CharField(blank=True, choices=[('cash', 'Cash Account'), ('bank', 'Bank Account'), ('credit', 'Credit Account')], help_text='Which finance account this payment was recorded in', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commission_paid_by', models.ForeignKey(blank=True, help_text='Who paid the commission to the seller', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_payments_made', to=settings.AUTH_USER_MODEL)),
                ('credit_company', models.ForeignKey(help_text='Select the credit company', on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='credit.creditcompany')),
                ('customer', models.ForeignKey(help_text='Customer who received the product', on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='credit.creditcustomer')),
                ('dealer', models.ForeignKey(help_text='Seller/Dealer who made the sale', on_delete=django.db.models.deletion.PROTECT, related_name='credit_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-transaction_date'],
            },
        ),
    ]
