# Generated by Django 6.0.2 on 2026-02-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcustomer',
            name='additional_document',
            field=models.FileField(blank=True, help_text='Any additional supporting document', null=True, upload_to='customers/documents/'),
        ),
        migrations.AddField(
            model_name='creditcustomer',
            name='id_back_photo',
            field=models.ImageField(blank=True, help_text='Back side of national ID', null=True, upload_to='customers/id_back/'),
        ),
        migrations.AddField(
            model_name='creditcustomer',
            name='id_front_photo',
            field=models.ImageField(blank=True, help_text='Front side of national ID', null=True, upload_to='customers/id_front/'),
        ),
        migrations.AddField(
            model_name='creditcustomer',
            name='passport_photo',
            field=models.ImageField(blank=True, help_text="Customer's passport photo", null=True, upload_to='customers/passports/'),
        ),
    ]
