# Generated by Django 5.1.6 on 2026-05-19 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credit', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='credittransaction',
            name='product',
            field=models.ForeignKey(help_text='Product sold on credit', on_delete=django.db.models.deletion.PROTECT, related_name='credit_transactions', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='credittransaction',
            name='reversed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_credit_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companypayment',
            name='transactions',
            field=models.ManyToManyField(related_name='company_payments', to='credit.credittransaction'),
        ),
        migrations.AddField(
            model_name='credittransactionlog',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='credittransactionlog',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='credit.credittransaction'),
        ),
        migrations.AddField(
            model_name='sellercommission',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_commissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sellercommission',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_commissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sellercommission',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions_earned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sellercommission',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_commission_record', to='credit.credittransaction'),
        ),
        migrations.AddField(
            model_name='sellercommissionsummary',
            name='seller',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission_summary', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='creditcustomer',
            index=models.Index(fields=['id_number'], name='credit_cred_id_numb_2ec113_idx'),
        ),
        migrations.AddIndex(
            model_name='creditcustomer',
            index=models.Index(fields=['phone_number'], name='credit_cred_phone_n_9b9016_idx'),
        ),
        migrations.AddIndex(
            model_name='creditcustomer',
            index=models.Index(fields=['full_name'], name='credit_cred_full_na_2cb682_idx'),
        ),
        migrations.AddIndex(
            model_name='credittransaction',
            index=models.Index(fields=['transaction_id'], name='credit_cred_transac_fd7ce3_idx'),
        ),
        migrations.AddIndex(
            model_name='credittransaction',
            index=models.Index(fields=['payment_status'], name='credit_cred_payment_78336e_idx'),
        ),
        migrations.AddIndex(
            model_name='credittransaction',
            index=models.Index(fields=['credit_company', 'payment_status'], name='credit_cred_credit__9cd243_idx'),
        ),
        migrations.AddIndex(
            model_name='credittransaction',
            index=models.Index(fields=['-transaction_date'], name='credit_cred_transac_8b1a9c_idx'),
        ),
        migrations.AddIndex(
            model_name='credittransaction',
            index=models.Index(fields=['etr_receipt_number'], name='credit_cred_etr_rec_40f808_idx'),
        ),
        migrations.AddIndex(
            model_name='credittransaction',
            index=models.Index(fields=['commission_status'], name='credit_cred_commiss_338a98_idx'),
        ),
        migrations.AddIndex(
            model_name='credittransaction',
            index=models.Index(fields=['dealer', 'commission_status'], name='credit_cred_dealer__0b584a_idx'),
        ),
        migrations.AddIndex(
            model_name='credittransaction',
            index=models.Index(fields=['partial_payment_amount'], name='credit_cred_partial_b86fb2_idx'),
        ),
        migrations.AddConstraint(
            model_name='credittransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('payment_status', 'pending'), ('payment_status', 'paid'), ('payment_status', 'partially_paid'), _connector='OR'), fields=('product',), name='unique_product_per_active_transaction'),
        ),
        migrations.AddIndex(
            model_name='sellercommission',
            index=models.Index(fields=['seller', 'status'], name='credit_sell_seller__a35a3a_idx'),
        ),
        migrations.AddIndex(
            model_name='sellercommission',
            index=models.Index(fields=['status'], name='credit_sell_status_ebace3_idx'),
        ),
    ]
