# Generated by Django 6.0.2 on 2026-03-11 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0002_creditcustomer_additional_document_and_more'),
        ('inventory', '0004_alter_stockalert_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Commission amount earned', max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SellerCommissionSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_earned', models.DecimalField(decimal_places=2, default=0, help_text='Total commissions earned (including paid and pending)', max_digits=12)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, help_text='Total commissions paid out', max_digits=12)),
                ('total_pending', models.DecimalField(decimal_places=2, default=0, help_text='Total commissions pending payment', max_digits=12)),
                ('last_paid_date', models.DateTimeField(blank=True, null=True)),
                ('last_paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transactions_count', models.IntegerField(default=0)),
                ('paid_transactions_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Seller Commission Summary',
                'verbose_name_plural': 'Seller Commission Summaries',
            },
        ),
        migrations.AddField(
            model_name='credittransaction',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Calculated commission amount (auto-filled)', max_digits=12),
        ),
        migrations.AddField(
            model_name='credittransaction',
            name='commission_notes',
            field=models.TextField(blank=True, help_text='Notes about commission payment'),
        ),
        migrations.AddField(
            model_name='credittransaction',
            name='commission_paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_payments_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='credittransaction',
            name='commission_paid_date',
            field=models.DateTimeField(blank=True, help_text='When commission was paid to seller', null=True),
        ),
        migrations.AddField(
            model_name='credittransaction',
            name='commission_status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid to Seller'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='credittransaction',
            name='commission_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', help_text='How commission is calculated', max_length=20),
        ),
        migrations.AddField(
            model_name='credittransaction',
            name='commission_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentage (e.g., 5 for 5%) or fixed amount in KSH', max_digits=10),
        ),
        migrations.AlterField(
            model_name='credittransactionlog',
            name='action',
            field=models.CharField(choices=[('created', 'Transaction Created'), ('paid', 'Paid by Company'), ('cancelled', 'Cancelled'), ('reversed', 'Reversed'), ('updated', 'Updated'), ('commission_paid', 'Commission Paid to Seller'), ('commission_cancelled', 'Commission Cancelled')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='credittransaction',
            index=models.Index(fields=['commission_status'], name='credit_cred_commiss_338a98_idx'),
        ),
        migrations.AddIndex(
            model_name='credittransaction',
            index=models.Index(fields=['dealer', 'commission_status'], name='credit_cred_dealer__0b584a_idx'),
        ),
        migrations.AddField(
            model_name='sellercommission',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_payouts_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sellercommission',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions_earned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sellercommission',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_commission_record', to='credit.credittransaction'),
        ),
        migrations.AddField(
            model_name='sellercommissionsummary',
            name='seller',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission_summary', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='sellercommission',
            index=models.Index(fields=['seller', 'status'], name='credit_sell_seller__a35a3a_idx'),
        ),
        migrations.AddIndex(
            model_name='sellercommission',
            index=models.Index(fields=['status'], name='credit_sell_status_ebace3_idx'),
        ),
    ]
