# Generated by Django 5.1.6 on 2026-05-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcustomer',
            name='nok_relationship',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
