# Generated by Django 5.1.6 on 2026-05-26 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0003_creditcustomer_nok_relationship'),
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credittransaction',
            name='product_sku',
            field=models.ForeignKey(blank=True, help_text='Product SKU (for bulk items)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_transactions', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='credittransaction',
            name='product',
            field=models.ForeignKey(help_text='Product unit sold on credit', on_delete=django.db.models.deletion.PROTECT, related_name='credit_transactions', to='inventory.productunit'),
        ),
    ]
