# Generated by Django 6.0.2 on 2026-03-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0003_sellercommission_sellercommissionsummary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credittransaction',
            name='commission_status',
            field=models.CharField(choices=[('not_applicable', 'Not Applicable'), ('requested', 'Requested'), ('approved', 'Approved'), ('paid', 'Paid to Seller'), ('cancelled', 'Cancelled')], default='not_applicable', max_length=20),
        ),
    ]
