# Generated by Django 6.0.2 on 2026-03-12 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0004_alter_credittransaction_commission_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credittransaction',
            name='commission_status',
            field=models.CharField(choices=[('not_set', 'Not Set'), ('requested', 'Requested'), ('approved', 'Approved'), ('paid', 'Paid to Seller'), ('cancelled', 'Cancelled')], default='not_set', max_length=20),
        ),
    ]
