# Generated by Django 6.0.2 on 2026-04-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0005_alter_credittransaction_commission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='credittransaction',
            name='finance_account_type',
            field=models.CharField(blank=True, choices=[('cash', 'Cash Account'), ('bank', 'Bank Account'), ('credit', 'Credit Account')], help_text='Which finance account this payment was recorded in', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='credittransaction',
            name='finance_transaction_id',
            field=models.CharField(blank=True, help_text='Link to FinancialTransaction in finance app', max_length=100, null=True),
        ),
    ]
