# Generated by Django 6.0.2 on 2026-04-07 19:34

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0007_sellercommission_approved_at_and_more'),
        ('inventory', '0006_returnrequest_loss_amount_returnrequest_loss_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='credittransaction',
            name='unique_product_per_active_transaction',
        ),
        migrations.AddField(
            model_name='credittransaction',
            name='partial_payment_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount already paid for partial payments (when company pays partially)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='credittransaction',
            name='commission_paid_by',
            field=models.ForeignKey(blank=True, help_text='Who paid the commission to the seller', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_payments_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='credittransaction',
            name='commission_status',
            field=models.CharField(choices=[('not_set', 'Not Set'), ('requested', 'Requested'), ('approved', 'Approved'), ('paid', 'Paid to Seller'), ('cancelled', 'Cancelled')], default='not_set', help_text="Status of seller's commission", max_length=20),
        ),
        migrations.AlterField(
            model_name='credittransaction',
            name='customer',
            field=models.ForeignKey(help_text='Customer who received the product', on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='credit.creditcustomer'),
        ),
        migrations.AlterField(
            model_name='credittransaction',
            name='dealer',
            field=models.ForeignKey(help_text='Seller/Dealer who made the sale', on_delete=django.db.models.deletion.PROTECT, related_name='credit_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='credittransaction',
            name='paid_date',
            field=models.DateTimeField(blank=True, help_text='When the company fully paid you', null=True),
        ),
        migrations.AlterField(
            model_name='credittransaction',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid by Company'), ('cancelled', 'Cancelled'), ('reversed', 'Reversed')], default='pending', help_text='Payment status from the credit company', max_length=20),
        ),
        migrations.AlterField(
            model_name='credittransaction',
            name='product',
            field=models.ForeignKey(help_text='Product sold on credit', on_delete=django.db.models.deletion.PROTECT, related_name='credit_transactions', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='credittransaction',
            name='product_code',
            field=models.CharField(blank=True, help_text='Product code at time of sale', max_length=100),
        ),
        migrations.AlterField(
            model_name='credittransaction',
            name='product_name',
            field=models.CharField(blank=True, help_text='Product name at time of sale', max_length=200),
        ),
        migrations.AlterField(
            model_name='credittransaction',
            name='transaction_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the credit transaction was created'),
        ),
        migrations.AlterField(
            model_name='credittransaction',
            name='transaction_id',
            field=models.CharField(db_index=True, help_text='Auto-generated transaction ID in format #SALE-XXXX', max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='credittransaction',
            index=models.Index(fields=['partial_payment_amount'], name='credit_cred_partial_b86fb2_idx'),
        ),
        migrations.AddConstraint(
            model_name='credittransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('payment_status', 'pending'), ('payment_status', 'paid'), ('payment_status', 'partially_paid'), _connector='OR'), fields=('product',), name='unique_product_per_active_transaction'),
        ),
    ]
