# Generated by Django 6.0.2 on 2026-02-18 11:35

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True, null=True)),
                ('tax_id', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_terms', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('item_type', models.CharField(choices=[('single', 'Single Item'), ('bulk', 'Bulk Item')], help_text='Single: Unique items (phones). Bulk: Stock items (cables)', max_length=10)),
                ('sku_type', models.CharField(choices=[('imei', 'IMEI NUMBER'), ('serial', 'SERIAL NUMBER')], help_text='Type of identifier for this category', max_length=10)),
                ('category_code', models.CharField(blank=True, max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='inventory_c_name_546ce4_idx'), models.Index(fields=['category_code'], name='inventory_c_categor_6b8bb3_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Product name (auto-generated from brand/model if blank)', max_length=255, null=True)),
                ('product_code', models.CharField(blank=True, db_index=True, max_length=20, unique=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('sales_count', models.PositiveIntegerField(default=0)),
                ('sku_value', models.CharField(blank=True, db_index=True, help_text='IMEI NUMBER OR SERIAL NUMBER - MUST BE UNIQUE for each unit', max_length=200, null=True, unique=True)),
                ('barcode', models.CharField(blank=True, db_index=True, help_text='Barcode for bulk items (optional for single items)', max_length=30, null=True, unique=True)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='1 for single items (auto-set), multiple for bulk items')),
                ('buying_price', models.DecimalField(decimal_places=2, help_text='Cost price (what you paid)', max_digits=12)),
                ('selling_price', models.DecimalField(decimal_places=2, help_text='Retail selling price (display price for customers)', max_digits=12)),
                ('best_price', models.DecimalField(blank=True, decimal_places=2, help_text='Wholesale selling price (used for bulk sales/discounts)', max_digits=10, null=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('status', models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('reserved', 'Reserved'), ('damaged', 'Damaged'), ('lowstock', 'Low Stock'), ('outofstock', 'Out of Stock')], default='available', max_length=20)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=200, null=True)),
                ('specifications', models.JSONField(blank=True, default=dict, help_text="Store RAM, storage, color, screen size, etc. Example: {'ram': '8GB', 'storage': '256GB', 'color': 'Black'}")),
                ('condition', models.CharField(choices=[('new', 'Brand New'), ('refurbished', 'Refurbished'), ('used', 'Used - Excellent'), ('used_good', 'Used - Good'), ('used_fair', 'Used - Fair')], default='new', max_length=20)),
                ('warranty_months', models.PositiveIntegerField(default=12, help_text='Warranty period in months')),
                ('description', models.TextField(blank=True, null=True)),
                ('reorder_level', models.PositiveIntegerField(blank=True, default=5, help_text='Minimum stock level before reordering (for bulk items only)', null=True)),
                ('last_restocked', models.DateTimeField(blank=True, help_text='When was this last restocked', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.category')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.supplier')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inventory.product')),
            ],
            options={
                'ordering': ['order', '-is_primary', 'created_at'],
                'unique_together': {('product', 'is_primary')},
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('rating', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='inventory.product')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', '-created_at'], name='inventory_p_product_8c0657_idx'), models.Index(fields=['rating'], name='inventory_p_rating_5b91a4_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_level', models.PositiveIntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('last_alerted', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='inventory.product')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('product', 'alert_level')},
            },
        ),
        migrations.CreateModel(
            name='StockEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Positive for stock IN, Negative for stock OUT')),
                ('entry_type', models.CharField(choices=[('purchase', 'Purchase'), ('sale', 'Sale'), ('reversal', 'Reversal'), ('adjustment', 'Adjustment')], max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit at time of transaction', max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total transaction value', max_digits=12)),
                ('reference_id', models.CharField(blank=True, help_text='Invoice/Receipt/Order number', max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_entries', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(help_text='Product this entry affects', on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Stock Entry',
                'verbose_name_plural': 'Stock Entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='inventory_s_created_3e718e_idx'), models.Index(fields=['entry_type'], name='inventory_s_entry_t_e83f6a_idx'), models.Index(fields=['product', '-created_at'], name='inventory_s_product_452578_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'status'], name='inventory_p_categor_3c59e3_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku_value'], name='inventory_p_sku_val_72a9b1_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['barcode'], name='inventory_p_barcode_3a77e5_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_code'], name='inventory_p_product_ee59bd_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand', 'model'], name='inventory_p_brand_fe0f2b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created_at'], name='inventory_p_created_711f60_idx'),
        ),
    ]
