# Generated by Django 6.0.2 on 2026-02-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, help_text='Barcode - Auto-generated if left blank', max_length=30, null=True, unique=True),
        ),
    ]
