# Generated by Django 5.1.6 on 2026-05-19 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='related_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='sales.sale'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_returns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockalert',
            name='dismissed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dismissed_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockalert',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='stockentry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockentry',
            name='product_sku',
            field=models.ForeignKey(blank=True, help_text='For bulk items without unique identifiers', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='stockentry',
            name='product_unit',
            field=models.ForeignKey(blank=True, help_text='For single items with unique identifiers', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', to='inventory.productunit'),
        ),
        migrations.AddField(
            model_name='productunit',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.supplier', verbose_name='Supplier'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.supplier', verbose_name='Supplier'),
        ),
        migrations.AlterUniqueTogether(
            name='productimage',
            unique_together={('product', 'is_primary')},
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['product', '-created_at'], name='inventory_p_product_8c0657_idx'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['rating'], name='inventory_p_rating_5b91a4_idx'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['is_verified'], name='inventory_p_is_veri_d5aa40_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['status'], name='inventory_r_status_ec036b_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['return_id'], name='inventory_r_return__2746ab_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['-requested_at'], name='inventory_r_request_07370f_idx'),
        ),
        migrations.AddIndex(
            model_name='stockalert',
            index=models.Index(fields=['product', 'is_active'], name='inventory_s_product_4acb5e_idx'),
        ),
        migrations.AddIndex(
            model_name='stockalert',
            index=models.Index(fields=['alert_type'], name='inventory_s_alert_t_af1483_idx'),
        ),
        migrations.AddIndex(
            model_name='stockentry',
            index=models.Index(fields=['-created_at'], name='inventory_s_created_3e718e_idx'),
        ),
        migrations.AddIndex(
            model_name='stockentry',
            index=models.Index(fields=['entry_type'], name='inventory_s_entry_t_e83f6a_idx'),
        ),
        migrations.AddIndex(
            model_name='stockentry',
            index=models.Index(fields=['product_sku', '-created_at'], name='inventory_s_product_d7ae3d_idx'),
        ),
        migrations.AddIndex(
            model_name='stockentry',
            index=models.Index(fields=['product_unit', '-created_at'], name='inventory_s_product_e6f14a_idx'),
        ),
        migrations.AddIndex(
            model_name='productunit',
            index=models.Index(fields=['imei_number'], name='inventory_p_imei_nu_9d763e_idx'),
        ),
        migrations.AddIndex(
            model_name='productunit',
            index=models.Index(fields=['serial_number'], name='inventory_p_serial__10e472_idx'),
        ),
        migrations.AddIndex(
            model_name='productunit',
            index=models.Index(fields=['status'], name='inventory_p_status_a57074_idx'),
        ),
        migrations.AddIndex(
            model_name='productunit',
            index=models.Index(fields=['product', 'status'], name='inventory_p_product_cd764a_idx'),
        ),
        migrations.AddIndex(
            model_name='productunit',
            index=models.Index(fields=['sold_date'], name='inventory_p_sold_da_b45742_idx'),
        ),
        migrations.AddIndex(
            model_name='productunit',
            index=models.Index(fields=['warranty_end'], name='inventory_p_warrant_78050a_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku_code'], name='inventory_p_sku_cod_d63a52_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand', 'model'], name='inventory_p_brand_fe0f2b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active'], name='inventory_p_categor_471092_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['available_quantity'], name='inventory_p_availab_bd9d1c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['selling_price'], name='inventory_p_selling_0096c5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('brand', 'model', 'specifications')},
        ),
    ]
