# Generated by Django 6.0.2 on 2026-02-22 20:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_product_barcode'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, unique=True)),
                ('product_code', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=255)),
                ('sku_value', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('reason', models.CharField(choices=[('defective', 'Defective Product'), ('wrong_item', 'Wrong Item Received'), ('changed_mind', 'Changed Mind'), ('damaged', 'Damaged During Shipping'), ('not_as_described', 'Not as Described'), ('other', 'Other')], max_length=50)),
                ('reason_text', models.TextField(blank=True, help_text='Additional details about the return', null=True)),
                ('etr_number', models.CharField(blank=True, help_text='ETR receipt number from sale', max_length=100, null=True)),
                ('sale_id', models.CharField(blank=True, help_text='Original sale ID', max_length=50, null=True)),
                ('reported_condition', models.CharField(choices=[('new', 'Like New'), ('good', 'Good'), ('fair', 'Fair'), ('damaged', 'Damaged')], default='good', max_length=20)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending Verification'), ('passed', 'Verification Passed'), ('failed', 'Verification Failed'), ('partial', 'Partial Match')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True, null=True)),
                ('physical_product_seen', models.BooleanField(default=False)),
                ('serial_number_matches', models.BooleanField(default=False)),
                ('condition_matches_report', models.BooleanField(default=False)),
                ('accessories_present', models.BooleanField(default=False)),
                ('box_present', models.BooleanField(default=False)),
                ('receipt_present', models.BooleanField(default=False)),
                ('product_photo_1', models.ImageField(blank=True, null=True, upload_to='returns/')),
                ('product_photo_2', models.ImageField(blank=True, null=True, upload_to='returns/')),
                ('product_photo_3', models.ImageField(blank=True, null=True, upload_to='returns/')),
                ('damage_photo', models.ImageField(blank=True, null=True, upload_to='returns/damage/')),
                ('system_sku', models.CharField(blank=True, help_text='SKU from system', max_length=200, null=True)),
                ('system_serial', models.CharField(blank=True, help_text='Serial from system', max_length=200, null=True)),
                ('system_condition', models.CharField(blank=True, help_text='Condition in system', max_length=50, null=True)),
                ('actual_sku', models.CharField(blank=True, max_length=200, null=True)),
                ('actual_serial', models.CharField(blank=True, max_length=200, null=True)),
                ('actual_condition', models.CharField(blank=True, choices=[('new', 'Like New'), ('good', 'Good'), ('fair', 'Fair'), ('damaged', 'Damaged'), ('different', 'Different Product')], max_length=20, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Submission'), ('submitted', 'Submitted - Awaiting Verification'), ('verified', 'Verified - Awaiting Approval'), ('approved', 'Approved - Awaiting Processing'), ('rejected', 'Rejected'), ('processed', 'Processed'), ('mismatch', 'Product Mismatch Detected')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_returns', to=settings.AUTH_USER_MODEL)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_returns', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='inventory.product')),
                ('related_sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='sales.sale')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_requests', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_returns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['status'], name='inventory_r_status_ec036b_idx'), models.Index(fields=['verification_status'], name='inventory_r_verific_d9eec5_idx'), models.Index(fields=['sale_id'], name='inventory_r_sale_id_16d9fc_idx'), models.Index(fields=['etr_number'], name='inventory_r_etr_num_db5cbc_idx'), models.Index(fields=['sku_value'], name='inventory_r_sku_val_9bb7ea_idx'), models.Index(fields=['product_code'], name='inventory_r_product_036f30_idx'), models.Index(fields=['-requested_at'], name='inventory_r_request_07370f_idx')],
            },
        ),
    ]
