# Generated by Django 5.1.6 on 2026-05-29 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_by_me', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_products', to=settings.AUTH_USER_MODEL)),
                ('product_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='inventory.productunit')),
            ],
            options={
                'verbose_name': 'Product Assignment',
                'verbose_name_plural': 'Product Assignments',
                'ordering': ['-assigned_at'],
                'indexes': [models.Index(fields=['assigned_to', 'is_active'], name='inventory_p_assigne_c451fa_idx'), models.Index(fields=['product_unit', 'is_active'], name='inventory_p_product_656843_idx'), models.Index(fields=['expires_at'], name='inventory_p_expires_534ca0_idx')],
                'unique_together': {('product_unit', 'assigned_to', 'is_active')},
            },
        ),
    ]
