# Generated by Django 6.0.2 on 2026-02-26 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_returnrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockalert',
            options={'ordering': ['-severity', '-created_at']},
        ),
        migrations.RenameField(
            model_name='stockalert',
            old_name='alert_level',
            new_name='threshold',
        ),
        migrations.AlterUniqueTogether(
            name='stockalert',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='stockalert',
            name='alert_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockalert',
            name='alert_type',
            field=models.CharField(choices=[('lowstock', 'Low Stock'), ('needs_reorder', 'Needs Reorder'), ('outofstock', 'Out of Stock'), ('expiring', 'Expiring Soon'), ('damaged', 'Damaged Stock')], default='lowstock', max_length=20),
        ),
        migrations.AddField(
            model_name='stockalert',
            name='current_stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockalert',
            name='dismissed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockalert',
            name='dismissed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dismissed_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockalert',
            name='dismissed_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockalert',
            name='is_dismissed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stockalert',
            name='reorder_level',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockalert',
            name='severity',
            field=models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('danger', 'Danger'), ('critical', 'Critical')], default='warning', max_length=20),
        ),
        migrations.AddIndex(
            model_name='stockalert',
            index=models.Index(fields=['product', 'is_active'], name='inventory_s_product_4acb5e_idx'),
        ),
        migrations.AddIndex(
            model_name='stockalert',
            index=models.Index(fields=['alert_type'], name='inventory_s_alert_t_af1483_idx'),
        ),
        migrations.AddIndex(
            model_name='stockalert',
            index=models.Index(fields=['severity'], name='inventory_s_severit_8239d2_idx'),
        ),
    ]
