# Generated by Django 6.0.2 on 2026-03-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_stockalert_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnrequest',
            name='return_id',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
