# Generated by Django 6.0.2 on 2026-03-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_returnrequest_return_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='loss_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual loss amount (usually buying price)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='loss_reason',
            field=models.CharField(blank=True, help_text='Reason for damage/loss', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Submission'), ('submitted', 'Submitted - Awaiting Verification'), ('verified', 'Verified - Awaiting Approval'), ('approved', 'Approved - Awaiting Processing'), ('rejected', 'Rejected'), ('processed', 'Processed (Restocked)'), ('damaged_loss', 'Damaged - Recorded as Loss'), ('mismatch', 'Product Mismatch Detected')], default='pending', max_length=20),
        ),
    ]
