# Generated by Django 6.0.2 on 2026-04-08 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_returnrequest_loss_amount_returnrequest_loss_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='insurance_claim_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount claimed from insurance', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='insurance_claim_filed',
            field=models.BooleanField(default=False, help_text='Has insurance claim been filed?'),
        ),
        migrations.AddField(
            model_name='product',
            name='insurance_claim_number',
            field=models.CharField(blank=True, help_text='Insurance claim reference number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='insurance_payout_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual amount received from insurance', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='insurance_payout_date',
            field=models.DateTimeField(blank=True, help_text='When insurance paid out', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_stolen_or_lost',
            field=models.BooleanField(default=False, help_text='Mark True if product is stolen or lost'),
        ),
        migrations.AddField(
            model_name='product',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, help_text='Last user who modified this product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='loss_notes',
            field=models.TextField(blank=True, help_text='Detailed description of the incident', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='loss_reported_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who reported the loss', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_losses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='loss_reported_date',
            field=models.DateTimeField(blank=True, help_text='When was the loss reported', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='loss_type',
            field=models.CharField(blank=True, choices=[('stolen', 'Stolen'), ('lost', 'Lost'), ('damaged_total', 'Totally Damaged'), ('expired', 'Expired'), ('recalled', 'Recalled')], help_text='Type of loss incident', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='police_report_number',
            field=models.CharField(blank=True, help_text='Police report reference number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='police_station',
            field=models.CharField(blank=True, help_text='Police station where report was filed', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='recovered_by',
            field=models.ForeignKey(blank=True, help_text='Who recovered the product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovered_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='recovered_date',
            field=models.DateTimeField(blank=True, help_text='If product was recovered after being stolen', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='recovery_notes',
            field=models.TextField(blank=True, help_text='Notes about recovery', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='reserved_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Quantity reserved for pending orders'),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('new', 'Brand New'), ('refurbished', 'Refurbished'), ('used', 'Used - Excellent'), ('used_good', 'Used - Good'), ('used_fair', 'Used - Fair'), ('damaged', 'Damaged - Not Sellable')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('reserved', 'Reserved'), ('damaged', 'Damaged'), ('lowstock', 'Low Stock'), ('outofstock', 'Out of Stock'), ('stolen', 'Stolen / Lost'), ('writeoff', 'Written Off'), ('recalled', 'Recalled by Manufacturer')], default='available', max_length=20),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_stolen_or_lost', 'loss_type'], name='inventory_p_is_stol_f7d596_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['loss_reported_date'], name='inventory_p_loss_re_8d336d_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['insurance_claim_filed'], name='inventory_p_insuran_d10aff_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status'], name='inventory_p_status_2ba142_idx'),
        ),
    ]
