# Generated by Django 6.0.2 on 2026-05-07 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_product_insurance_claim_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='inventory_p_sku_val_72a9b1_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='inventory_p_created_711f60_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='inventory_p_status_2ba142_idx',
        ),
        migrations.AddField(
            model_name='product',
            name='imei_number',
            field=models.CharField(blank=True, db_index=True, help_text='15-digit IMEI number (for phones)', max_length=15, null=True, unique=True, verbose_name='IMEI Number'),
        ),
        migrations.AddField(
            model_name='product',
            name='serial_number',
            field=models.CharField(blank=True, db_index=True, help_text='Unique serial number for this specific item', max_length=200, null=True, unique=True, verbose_name='Serial Number'),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, help_text='Scannable barcode for product data', max_length=30, null=True, unique=True, verbose_name='Barcode'),
        ),
        migrations.AlterField(
            model_name='product',
            name='best_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Best/Retail Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Product Brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='buying_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Buying Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.category', verbose_name='Product Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('new', 'Brand New'), ('refurbished', 'Refurbished'), ('used', 'Used - Excellent'), ('used_good', 'Used - Good'), ('used_fair', 'Used - Fair'), ('damaged', 'Damaged - Not Sellable')], default='new', max_length=20, verbose_name='Product Condition'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='insurance_claim_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount claimed from insurance', max_digits=12, null=True, verbose_name='Insurance Claim Amount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='insurance_claim_filed',
            field=models.BooleanField(default=False, help_text='Has insurance claim been filed?', verbose_name='Insurance Claim Filed'),
        ),
        migrations.AlterField(
            model_name='product',
            name='insurance_claim_number',
            field=models.CharField(blank=True, help_text='Insurance claim reference number', max_length=100, null=True, verbose_name='Insurance Claim Number'),
        ),
        migrations.AlterField(
            model_name='product',
            name='insurance_payout_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual amount received from insurance', max_digits=12, null=True, verbose_name='Insurance Payout Amount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='insurance_payout_date',
            field=models.DateTimeField(blank=True, help_text='When insurance paid out', null=True, verbose_name='Insurance Payout Date'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_stolen_or_lost',
            field=models.BooleanField(default=False, help_text='Mark True if product is stolen or lost', verbose_name='Is Stolen or Lost'),
        ),
        migrations.AlterField(
            model_name='product',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, help_text='Last user who modified this product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_products', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AlterField(
            model_name='product',
            name='last_restocked',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Restocked'),
        ),
        migrations.AlterField(
            model_name='product',
            name='loss_notes',
            field=models.TextField(blank=True, help_text='Detailed description of the incident', null=True, verbose_name='Loss Notes'),
        ),
        migrations.AlterField(
            model_name='product',
            name='loss_reported_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who reported the loss', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_losses', to=settings.AUTH_USER_MODEL, verbose_name='Loss Reported By'),
        ),
        migrations.AlterField(
            model_name='product',
            name='loss_reported_date',
            field=models.DateTimeField(blank=True, help_text='When was the loss reported', null=True, verbose_name='Loss Reported Date'),
        ),
        migrations.AlterField(
            model_name='product',
            name='loss_type',
            field=models.CharField(blank=True, choices=[('stolen', 'Stolen'), ('lost', 'Lost'), ('damaged_total', 'Totally Damaged'), ('expired', 'Expired'), ('recalled', 'Recalled')], help_text='Type of loss incident', max_length=20, null=True, verbose_name='Loss Type'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Product Model'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, help_text='Product name (auto-generated from brand/model if blank)', max_length=255, null=True, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='Product Owner'),
        ),
        migrations.AlterField(
            model_name='product',
            name='police_report_number',
            field=models.CharField(blank=True, help_text='Police report reference number', max_length=100, null=True, verbose_name='Police Report Number'),
        ),
        migrations.AlterField(
            model_name='product',
            name='police_station',
            field=models.CharField(blank=True, help_text='Police station where report was filed', max_length=200, null=True, verbose_name='Police Station'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(blank=True, db_index=True, help_text='Unique product identifier (F00101, F00102, etc.)', max_length=20, unique=True, verbose_name='SKU/Product Code'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='1 for single items (auto-set), multiple for bulk items', verbose_name='Product Quantity'),
        ),
        migrations.AlterField(
            model_name='product',
            name='recovered_by',
            field=models.ForeignKey(blank=True, help_text='Who recovered the product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovered_products', to=settings.AUTH_USER_MODEL, verbose_name='Recovered By'),
        ),
        migrations.AlterField(
            model_name='product',
            name='recovered_date',
            field=models.DateTimeField(blank=True, help_text='If product was recovered after being stolen', null=True, verbose_name='Recovered Date'),
        ),
        migrations.AlterField(
            model_name='product',
            name='recovery_notes',
            field=models.TextField(blank=True, help_text='Notes about recovery', null=True, verbose_name='Recovery Notes'),
        ),
        migrations.AlterField(
            model_name='product',
            name='reorder_level',
            field=models.PositiveIntegerField(blank=True, default=5, help_text='Minimum stock level before reordering (for bulk items only)', null=True, verbose_name='Reorder Level'),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Selling Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku_value',
            field=models.CharField(blank=True, db_index=True, help_text='Legacy field - Use product_code instead', max_length=200, null=True, verbose_name='SKU Value (Legacy)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=models.JSONField(blank=True, default=dict, help_text="RAM, storage, color, screen size, etc. Example: {'ram': '8GB', 'storage': '256GB', 'color': 'Black'}", verbose_name='Specifications'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('reserved', 'Reserved'), ('damaged', 'Damaged'), ('lowstock', 'Low Stock'), ('outofstock', 'Out of Stock'), ('stolen', 'Stolen / Lost'), ('writeoff', 'Written Off'), ('recalled', 'Recalled by Manufacturer')], default='available', max_length=20, verbose_name='Product Status'),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.supplier', verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='product',
            name='warranty_months',
            field=models.PositiveIntegerField(default=12, verbose_name='Warranty (Months)'),
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='entry_type',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('sale', 'Sale'), ('reversal', 'Reversal'), ('adjustment', 'Adjustment'), ('return', 'Customer Return')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['serial_number'], name='inventory_p_serial__7bcc99_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['imei_number'], name='inventory_p_imei_nu_55d9c7_idx'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sales_count',
        ),
        migrations.RemoveField(
            model_name='product',
            name='view_count',
        ),
    ]
