# Generated by Django 6.0.2 on 2026-05-07 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_product_inventory_p_sku_val_72a9b1_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('category', 'imei_number'), ('category', 'serial_number')},
        ),
    ]
