# Generated by Django 6.0.2 on 2026-05-19 15:11

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('location', models.CharField(max_length=200)),
                ('manager', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('opening_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Shop Branches',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DailyShopReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('submission_time', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('total_mpesa_transactions', models.PositiveIntegerField(default=0)),
                ('total_mpesa_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_closing_balance', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('cash_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Cash Balance')),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_finalized', models.BooleanField(default=False)),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_reports', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reports', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='shops.shopbranch')),
            ],
            options={
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='MpesaAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(help_text='Name to identify this account', max_length=100)),
                ('account_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('account_type', models.CharField(choices=[('till', 'Till Number'), ('paybill', 'Paybill Number'), ('agent', 'Agent Number'), ('merchant', 'Merchant Account')], default='till', max_length=20)),
                ('store_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Store Number')),
                ('total_deposit_count', models.PositiveIntegerField(default=0, verbose_name='Total Deposits Count')),
                ('total_withdrawal_count', models.PositiveIntegerField(default=0, verbose_name='Total Withdrawals Count')),
                ('total_sale_count', models.PositiveIntegerField(default=0, verbose_name='Total Sales Count')),
                ('total_deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_withdrawal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_sale_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('phone_number', models.CharField(blank=True, help_text='Registered M-Pesa phone number', max_length=12, null=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, help_text='Initial float amount', max_digits=12)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, help_text='Current available balance', max_digits=12)),
                ('daily_limit', models.DecimalField(decimal_places=2, default=500000, help_text='Daily transaction limit', max_digits=12)),
                ('per_transaction_limit', models.DecimalField(decimal_places=2, default=150000, help_text='Per transaction limit', max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], db_index=True, default='active', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('business_hours_start', models.TimeField(blank=True, default='08:00', null=True)),
                ('business_hours_end', models.TimeField(blank=True, default='22:00', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_mpesa_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Assigned User/Cashier')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_mpesa_accounts', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_mpesa_accounts', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_accounts', to='shops.shopbranch')),
            ],
            options={
                'verbose_name': 'M-Pesa Account',
                'verbose_name_plural': 'M-Pesa Accounts',
                'ordering': ['shop__name', 'account_name'],
            },
        ),
        migrations.CreateModel(
            name='CashAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(default='Main Cash', help_text='e.g., Main Cash, Petty Cash', max_length=100)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_accounts', to='shops.shopbranch')),
            ],
            options={
                'ordering': ['account_name'],
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='shops.shopbranch')),
            ],
            options={
                'ordering': ['bank_name'],
            },
        ),
        migrations.CreateModel(
            name='ShopConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_type', models.CharField(choices=[('general', 'General Settings'), ('reporting', 'Reporting Settings'), ('notifications', 'Notification Settings'), ('limits', 'Limit Settings')], default='general', max_length=50)),
                ('config_key', models.CharField(max_length=100)),
                ('config_value', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='shops.shopbranch')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['config_type', 'config_key'],
            },
        ),
        migrations.CreateModel(
            name='ShopExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_category', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('bank', 'Bank Transfer'), ('cheque', 'Cheque')], default='cash', max_length=50)),
                ('receipt_number', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='shops.bankaccount')),
                ('cash_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='shops.cashaccount')),
                ('daily_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='shops.dailyshopreport')),
                ('mpesa_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='shops.mpesaaccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankDailyBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_deposits', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_withdrawals', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transaction_count', models.PositiveIntegerField(default=0)),
                ('variance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_reconciled', models.BooleanField(default=False)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_balances', to='shops.bankaccount')),
                ('reconciled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-report_date'],
                'unique_together': {('bank_account', 'report_date')},
            },
        ),
        migrations.CreateModel(
            name='CashDailyBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cash_in', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cash_out', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transaction_count', models.PositiveIntegerField(default=0)),
                ('variance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_reconciled', models.BooleanField(default=False)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cash_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_balances', to='shops.cashaccount')),
                ('reconciled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-report_date'],
                'unique_together': {('cash_account', 'report_date')},
            },
        ),
        migrations.CreateModel(
            name='BankClosingBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.bankaccount')),
                ('daily_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_closings', to='shops.dailyshopreport')),
            ],
            options={
                'verbose_name_plural': 'Bank Closing Balances',
                'unique_together': {('daily_report', 'bank_account')},
            },
        ),
        migrations.CreateModel(
            name='DynamicChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_type', models.CharField(choices=[('bank_name', 'Bank Name'), ('mpesa_account_type', 'M-Pesa Account Type'), ('expense_category', 'Expense Category'), ('payment_method', 'Payment Method')], max_length=50)),
                ('value', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['choice_type', 'value'],
                'unique_together': {('choice_type', 'value')},
            },
        ),
        migrations.CreateModel(
            name='DailyMpesaAccountReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closing_mpesa_float', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('closing_airtel_float', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('closing_cash', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transaction_count', models.PositiveIntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('daily_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_balances', to='shops.dailyshopreport')),
                ('mpesa_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='shops.mpesaaccount')),
            ],
            options={
                'ordering': ['mpesa_account__account_name'],
                'unique_together': {('daily_report', 'mpesa_account')},
            },
        ),
        migrations.CreateModel(
            name='MpesaDailyBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('opening_mpesa_float', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('opening_airtel_float', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('opening_cash', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('closing_mpesa_float', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('closing_airtel_float', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('closing_cash', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_deposits', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_withdrawals', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transaction_count', models.PositiveIntegerField(default=0)),
                ('mpesa_variance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('airtel_variance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cash_variance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_reconciled', models.BooleanField(default=False)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mpesa_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_balances', to='shops.mpesaaccount')),
                ('reconciled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-report_date'],
                'unique_together': {('mpesa_account', 'report_date')},
            },
        ),
        migrations.AddIndex(
            model_name='mpesaaccount',
            index=models.Index(fields=['account_number'], name='shops_mpesa_account_c41a7a_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesaaccount',
            index=models.Index(fields=['shop', 'status'], name='shops_mpesa_shop_id_83d4de_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesaaccount',
            index=models.Index(fields=['account_type'], name='shops_mpesa_account_15f9ff_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyshopreport',
            unique_together={('shop', 'report_date')},
        ),
        migrations.AlterUniqueTogether(
            name='cashaccount',
            unique_together={('shop', 'account_name')},
        ),
        migrations.AlterUniqueTogether(
            name='bankaccount',
            unique_together={('shop', 'bank_name', 'account_number')},
        ),
        migrations.AlterUniqueTogether(
            name='shopconfiguration',
            unique_together={('shop', 'config_key')},
        ),
    ]
