# Generated by Django 6.0.2 on 2026-04-09 09:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('location', models.CharField(max_length=200)),
                ('manager', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('opening_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Shop Branches',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DailyShopReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('submission_time', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('closing_mpesa_float', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Closing M-Pesa Float')),
                ('closing_mpesa_cash', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Closing M-Pesa Cash')),
                ('shop_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Daily Shop Sales')),
                ('total_closing_balance', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_finalized', models.BooleanField(default=False)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='shops.shopbranch')),
            ],
            options={
                'verbose_name_plural': 'Daily Shop Reports',
                'ordering': ['-report_date'],
                'unique_together': {('shop', 'report_date')},
            },
        ),
        migrations.CreateModel(
            name='MpesaAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=50, unique=True)),
                ('account_type', models.CharField(max_length=50)),
                ('phone_number', models.CharField(help_text='Registered M-Pesa phone number', max_length=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_accounts', to='shops.shopbranch')),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='shops.shopbranch')),
            ],
            options={
                'ordering': ['bank_name'],
                'unique_together': {('shop', 'bank_name', 'account_number')},
            },
        ),
        migrations.CreateModel(
            name='ShopExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_category', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_method', models.CharField(default='cash', max_length=50)),
                ('receipt_number', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('daily_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='shops.dailyshopreport')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankClosingBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.bankaccount')),
                ('daily_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_closings', to='shops.dailyshopreport')),
            ],
            options={
                'verbose_name_plural': 'Bank Closing Balances',
                'unique_together': {('daily_report', 'bank_account')},
            },
        ),
        migrations.CreateModel(
            name='DynamicChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_type', models.CharField(choices=[('bank_name', 'Bank Name'), ('mpesa_account_type', 'M-Pesa Account Type'), ('expense_category', 'Expense Category'), ('payment_method', 'Payment Method')], max_length=50)),
                ('value', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['choice_type', 'value'],
                'unique_together': {('choice_type', 'value')},
            },
        ),
        migrations.CreateModel(
            name='MpesaDailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('opening_float', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('float_added', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('float_withdrawn', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('customer_payments', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cash_out_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('closing_float', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('opening_cash', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cash_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cash_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cash_withdrawn', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('closing_cash', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expected_float', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('float_variance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expected_cash', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cash_variance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_reconciled', models.BooleanField(default=False)),
                ('reconciliation_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('daily_report', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_summary', to='shops.dailyshopreport')),
                ('reconciled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_reconciliations', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_summaries', to='shops.shopbranch')),
            ],
            options={
                'ordering': ['-report_date'],
                'unique_together': {('shop', 'report_date')},
            },
        ),
        migrations.CreateModel(
            name='ShopConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_key', models.CharField(max_length=100)),
                ('config_value', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='shops.shopbranch')),
            ],
            options={
                'unique_together': {('shop', 'config_key')},
            },
        ),
    ]
