# Generated by Django 6.0.2 on 2026-04-10 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyshopreport',
            name='shop_sales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total M-Pesa Transactions'),
        ),
        migrations.AlterField(
            model_name='shopexpense',
            name='expense_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shopexpense',
            name='payment_method',
            field=models.CharField(blank=True, default='cash', max_length=50),
        ),
    ]
