# Generated by Django 5.1.6 on 2026-05-25 08:24

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesaaccount',
            name='total_injections_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='mpesaaccount',
            name='total_injections_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Manual Injections Count'),
        ),
        migrations.AddField(
            model_name='mpesaaccount',
            name='total_manual_withdrawals_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='mpesaaccount',
            name='total_manual_withdrawals_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Manual Withdrawals Count'),
        ),
        migrations.CreateModel(
            name='MpesaAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('injection', 'Injection (Add Money)'), ('withdrawal', 'Withdrawal (Take Money Out)')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('reference_number', models.CharField(blank=True, help_text='Transaction reference or receipt number', max_length=100, null=True)),
                ('reason', models.TextField(help_text="Reason for this adjustment (e.g., 'Extra cash injection from owner', 'Cash taken for expenses')")),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_mpesa_adjustments', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_adjustments', to=settings.AUTH_USER_MODEL)),
                ('daily_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_adjustments', to='shops.dailyshopreport')),
                ('mpesa_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='shops.mpesaaccount')),
            ],
            options={
                'verbose_name': 'M-Pesa Adjustment',
                'verbose_name_plural': 'M-Pesa Adjustments',
                'ordering': ['-created_at'],
            },
        ),
    ]
