# Generated by Django 5.1.6 on 2026-05-26 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_accounttransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shopexpense',
            name='is_recovered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shopexpense',
            name='recovered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopexpense',
            name='recovered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovered_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shopexpense',
            name='recovery_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
