# Generated by Django 6.0.2 on 2026-04-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_dailyshopreport_finalized_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyshopreport',
            name='closing_airtel_float',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Closing Airtel Float'),
        ),
    ]
