# Generated by Django 6.0.2 on 2026-05-03 20:45

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0004_dailyshopreport_closing_airtel_float'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepairJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('device_type', models.CharField(max_length=50)),
                ('device_model', models.CharField(blank=True, max_length=100, null=True)),
                ('issue_description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('picked_up', 'Picked Up'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('material_cost', models.DecimalField(decimal_places=2, default=0.0, help_text='Cost of materials used for repair', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0.0, help_text='Labor/service charges', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Total amount customer needs to pay (material + labor)', max_digits=10, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount already paid by customer', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('remaining_balance', models.DecimalField(blank=True, decimal_places=2, help_text='Remaining amount to be paid', max_digits=10, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('bank', 'Bank Transfer'), ('mixed', 'Mixed')], default='cash', max_length=50, null=True)),
                ('mpesa_transaction_code', models.CharField(blank=True, max_length=50, null=True)),
                ('technician_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('warranty_days', models.IntegerField(default=30, help_text='Warranty period in days')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repair_jobs', to='shops.shopbranch', verbose_name='Shop Branch')),
            ],
            options={
                'verbose_name_plural': 'Repair Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RepairJobExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_incurred', models.DateTimeField(auto_now_add=True)),
                ('repair_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='workshop.repairjob')),
            ],
        ),
    ]
