# Generated by Django 6.0.2 on 2026-02-18 11:35

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleCounter',
            fields=[
                ('year', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('counter', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Sale Counter',
                'verbose_name_plural': 'Sale Counters',
                'db_table': 'sale_counters',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('batch_id', models.CharField(blank=True, max_length=50, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sale_id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('sale_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('buyer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('buyer_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('buyer_id_number', models.CharField(blank=True, max_length=50, null=True)),
                ('nok_name', models.CharField(blank=True, max_length=200, null=True)),
                ('nok_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('total_quantity', models.PositiveIntegerField(default=0)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('etr_receipt_number', models.CharField(blank=True, help_text='ETR receipt number in format Rcpt_No:0001', max_length=100, null=True, unique=True)),
                ('etr_receipt_counter', models.PositiveIntegerField(blank=True, db_index=True, help_text='Sequential counter for ETR receipts (1, 2, 3...)', null=True)),
                ('fiscal_receipt_number', models.CharField(blank=True, help_text='Fiscal receipt number', max_length=100, null=True, unique=True)),
                ('etr_status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('is_credit', models.BooleanField(default=False, help_text='Whether this sale is on credit')),
                ('credit_sale_id', models.CharField(blank=True, help_text='Reference to credit app sale ID', max_length=50, null=True)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('M-Pesa', 'M-Pesa'), ('Card', 'Card'), ('Points', 'Points'), ('Credit', 'Credit')], default='Cash', max_length=20)),
                ('etr_processed_at', models.DateTimeField(blank=True, null=True)),
                ('etr_error_message', models.TextField(blank=True, null=True)),
                ('is_reversed', models.BooleanField(default=False)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('reversal_reason', models.TextField(blank=True, null=True)),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_sales', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sales',
                'ordering': ['-sale_date'],
            },
        ),
        migrations.CreateModel(
            name='FiscalReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=100, unique=True)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('qr_code', models.TextField(blank=True, null=True)),
                ('verification_url', models.URLField(blank=True, null=True)),
                ('receipt_data', models.TextField(blank=True, null=True)),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_receipt', to='sales.sale')),
            ],
            options={
                'verbose_name': 'Fiscal Receipt',
                'verbose_name_plural': 'Fiscal Receipts',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=255)),
                ('sku_value', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_age_days', models.PositiveIntegerField(default=0, help_text='Age of product when sold (for FIFO verification)')),
                ('product', models.ForeignKey(help_text='Product sold', on_delete=django.db.models.deletion.CASCADE, related_name='sale_items', to='inventory.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale')),
            ],
            options={
                'db_table': 'sale_items',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SaleReversal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reversed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('items_processed', models.PositiveIntegerField(default=0, help_text='Number of items reversed')),
                ('total_amount_reversed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount reversed', max_digits=12)),
                ('reversal_reference', models.CharField(blank=True, help_text='Reference ID for the reversal transaction', max_length=100, null=True)),
                ('reversed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_reversals', to=settings.AUTH_USER_MODEL)),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reversal', to='sales.sale')),
            ],
            options={
                'verbose_name': 'Sale Reversal',
                'verbose_name_plural': 'Sale Reversals',
                'ordering': ['-reversed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['-sale_date'], name='sales_sale_da_42086e_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['seller', '-sale_date'], name='sales_seller__6dfae4_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['etr_receipt_number'], name='sales_etr_rec_0155e5_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['etr_receipt_counter'], name='sales_etr_rec_e4057a_idx'),
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['sale', 'product'], name='sale_items_sale_id_02f224_idx'),
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['product'], name='sale_items_product_f7cd9c_idx'),
        ),
    ]
