# Generated by Django 6.0.2 on 2026-03-17 08:17

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_purchase_for_points', models.PositiveIntegerField(default=100, help_text='Minimum purchase amount to earn points')),
                ('points_per_unit', models.PositiveIntegerField(default=100, help_text='KSH spent per point (e.g., 100 = 1 point per 100 KSH)')),
                ('max_points_per_transaction', models.PositiveIntegerField(default=100, help_text='Maximum points that can be earned in a single transaction')),
                ('min_redeem_points', models.PositiveIntegerField(default=1, help_text='Minimum points required to redeem')),
                ('max_redeem_percentage', models.PositiveIntegerField(default=100, help_text='Maximum percentage of sale that can be paid with points (100% = full payment)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('points_expiry_days', models.PositiveIntegerField(default=365, help_text='Number of days before points expire')),
                ('welcome_points', models.PositiveIntegerField(default=10, help_text='Points awarded to new customers')),
            ],
            options={
                'verbose_name': 'Loyalty Settings',
                'verbose_name_plural': 'Loyalty Settings',
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='original_subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Original subtotal before points discount', max_digits=12),
        ),
        migrations.AddField(
            model_name='sale',
            name='points_discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount amount from points redemption', max_digits=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='points_redeemed',
            field=models.IntegerField(default=0, help_text='Points redeemed in this sale'),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('id_number', models.CharField(blank=True, max_length=50, null=True)),
                ('points_balance', models.IntegerField(default=0, help_text='Current loyalty points balance (1 point = KSH 1)')),
                ('total_points_earned', models.IntegerField(default=0, help_text='Total points earned all time')),
                ('total_points_redeemed', models.IntegerField(default=0, help_text='Total points redeemed')),
                ('tier', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='bronze', max_length=20)),
                ('total_purchases', models.PositiveIntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_purchase_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_number'], name='sales_custo_phone_n_2cfbb3_idx'), models.Index(fields=['tier'], name='sales_custo_tier_589bf9_idx'), models.Index(fields=['-total_spent'], name='sales_custo_total_s_d9d113_idx')],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('transaction_type', models.CharField(choices=[('earned', 'Points Earned'), ('redeemed', 'Points Redeemed'), ('expired', 'Points Expired'), ('adjusted', 'Manual Adjustment')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_transactions', to='sales.customer')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_transactions', to='sales.sale')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', '-created_at'], name='sales_loyal_custome_86c625_idx'), models.Index(fields=['sale'], name='sales_loyal_sale_id_012bd8_idx')],
            },
        ),
    ]
