# Generated by Django 5.1.6 on 2026-05-27 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale_cart_snapshot_sale_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
