# Generated by Django 6.0.2 on 2026-03-17 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_loyaltysettings_sale_original_subtotal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-created_at'], 'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='loyaltytransaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Loyalty Transaction', 'verbose_name_plural': 'Loyalty Transactions'},
        ),
        migrations.AddField(
            model_name='customer',
            name='registered_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who registered this customer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_customers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='registration_note',
            field=models.TextField(blank=True, help_text='Additional notes about registration', null=True),
        ),
        migrations.AddField(
            model_name='loyaltysettings',
            name='require_email_for_registration',
            field=models.BooleanField(default=False, help_text='Require email for customer registration'),
        ),
        migrations.AddField(
            model_name='loyaltysettings',
            name='require_id_for_registration',
            field=models.BooleanField(default=False, help_text='Require ID number for customer registration'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Registration date'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, help_text='Optional email address', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='full_name',
            field=models.CharField(default='Unknown Customer', help_text="Customer's full name", max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id_number',
            field=models.CharField(blank=True, help_text='National ID or passport number', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether customer is active'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_purchase_date',
            field=models.DateTimeField(blank=True, help_text='Date of most recent purchase', null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(db_index=True, help_text='Unique phone number used for customer identification', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='total_purchases',
            field=models.PositiveIntegerField(default=0, help_text='Number of purchases made'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='total_spent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total amount spent in KSH', max_digits=12),
        ),
        migrations.AlterField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last updated'),
        ),
        migrations.AlterField(
            model_name='loyaltysettings',
            name='welcome_points',
            field=models.PositiveIntegerField(default=10, help_text='Points awarded to new customers on registration'),
        ),
        migrations.AlterField(
            model_name='loyaltytransaction',
            name='points',
            field=models.IntegerField(help_text='Positive for earned, negative for redeemed'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['-created_at'], name='sales_custo_created_0b77c9_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltytransaction',
            index=models.Index(fields=['transaction_type'], name='sales_loyal_transac_267380_idx'),
        ),
    ]
