# Generated by Django 6.0.2 on 2026-03-31 07:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_customer_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='salereversal',
            index=models.Index(fields=['-reversed_at'], name='sales_saler_reverse_4c9072_idx'),
        ),
        migrations.AddIndex(
            model_name='salereversal',
            index=models.Index(fields=['sale'], name='sales_saler_sale_id_0caa4c_idx'),
        ),
    ]
