# Generated by Django 6.0.2 on 2026-04-23 17:35

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_salereversal_sales_saler_reverse_4c9072_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customer',
            name='sales_custo_tier_589bf9_idx',
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='sales_custo_total_s_d9d113_idx',
        ),
        migrations.RemoveIndex(
            model_name='loyaltytransaction',
            name='sales_loyal_transac_267380_idx',
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='full_name',
            field=models.CharField(default='Unknown Customer', max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_purchase_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='points_balance',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), help_text='Current loyalty points balance (1 point = KSH 100)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='registered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_customers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customer',
            name='total_points_earned',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), help_text='Total points earned all time', max_digits=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='total_points_redeemed',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), help_text='Total points redeemed', max_digits=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='total_purchases',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='total_spent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='loyaltysettings',
            name='max_points_per_transaction',
            field=models.PositiveIntegerField(default=10000, help_text='Maximum points that can be earned in a single transaction'),
        ),
        migrations.AlterField(
            model_name='loyaltysettings',
            name='max_redeem_percentage',
            field=models.PositiveIntegerField(default=100, help_text='Maximum percentage of sale that can be paid with points', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='loyaltysettings',
            name='min_purchase_for_points',
            field=models.PositiveIntegerField(default=100, help_text='Minimum purchase amount to earn points (KSH)'),
        ),
        migrations.AlterField(
            model_name='loyaltytransaction',
            name='points',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), help_text='Positive for earned, negative for redeemed', max_digits=10),
        ),
        migrations.RemoveField(
            model_name='customer',
            name='registration_note',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='tier',
        ),
    ]
