# Generated by Django 6.0.2 on 2026-04-23 18:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_remove_customer_sales_custo_tier_589bf9_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='registration_note',
            field=models.TextField(blank=True, help_text='Additional notes about registration', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='tier',
            field=models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='bronze', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Registration date'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, help_text='Optional email address', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='full_name',
            field=models.CharField(default='Unknown Customer', help_text="Customer's full name", max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id_number',
            field=models.CharField(blank=True, help_text='National ID or passport number', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether customer is active'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_purchase_date',
            field=models.DateTimeField(blank=True, help_text='Date of most recent purchase', null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='points_balance',
            field=models.IntegerField(default=0, help_text='Current loyalty points balance (1 point = KSH 1)'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='registered_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who registered this customer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_customers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customer',
            name='total_points_earned',
            field=models.IntegerField(default=0, help_text='Total points earned all time'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='total_points_redeemed',
            field=models.IntegerField(default=0, help_text='Total points redeemed'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='total_purchases',
            field=models.PositiveIntegerField(default=0, help_text='Number of purchases made'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='total_spent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total amount spent in KSH', max_digits=12),
        ),
        migrations.AlterField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last updated'),
        ),
        migrations.AlterField(
            model_name='loyaltysettings',
            name='max_points_per_transaction',
            field=models.PositiveIntegerField(default=100, help_text='Maximum points that can be earned in a single transaction'),
        ),
        migrations.AlterField(
            model_name='loyaltysettings',
            name='max_redeem_percentage',
            field=models.PositiveIntegerField(default=100, help_text='Maximum percentage of sale that can be paid with points (100% = full payment)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='loyaltysettings',
            name='min_purchase_for_points',
            field=models.PositiveIntegerField(default=100, help_text='Minimum purchase amount to earn points'),
        ),
        migrations.AlterField(
            model_name='loyaltytransaction',
            name='points',
            field=models.IntegerField(help_text='Positive for earned, negative for redeemed'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['tier'], name='sales_custo_tier_589bf9_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['-total_spent'], name='sales_custo_total_s_d9d113_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltytransaction',
            index=models.Index(fields=['transaction_type'], name='sales_loyal_transac_267380_idx'),
        ),
    ]
