# Generated by Django 6.0.2 on 2026-04-23 19:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_remove_customer_sales_custo_tier_589bf9_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loyaltysettings',
            name='points_per_unit',
        ),
        migrations.AddField(
            model_name='loyaltysettings',
            name='points_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Percentage of sale to award as points (e.g., 1.00 = 1%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='customer',
            name='points_balance',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), help_text='Current loyalty points balance (1 point = KSH 1 value)', max_digits=10),
        ),
    ]
