# Generated by Django 6.0.2 on 2026-05-06 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_remove_loyaltysettings_points_per_unit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='is_split_payment',
            field=models.BooleanField(default=False, help_text='Whether this sale used multiple payment methods'),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_breakdown',
            field=models.JSONField(blank=True, default=dict, help_text='JSON breakdown of split payments', null=True),
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('Cash', 'Cash'), ('M-Pesa', 'M-Pesa'), ('Card', 'Card/Bank'), ('Points', 'Loyalty Points')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cash_tendered', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cash_change', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mpesa_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('mpesa_transaction_id', models.CharField(blank=True, max_length=50, null=True)),
                ('mpesa_checkout_request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=50, null=True)),
                ('card_last_four', models.CharField(blank=True, max_length=4, null=True)),
                ('points_redeemed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payments', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to='sales.sale')),
            ],
            options={
                'verbose_name': 'Payment Record',
                'verbose_name_plural': 'Payment Records',
                'db_table': 'payment_records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sale', 'method'], name='payment_rec_sale_id_34eb50_idx'), models.Index(fields=['mpesa_transaction_id'], name='payment_rec_mpesa_t_83d228_idx')],
            },
        ),
    ]
