# Generated by Django 6.0.2 on 2026-05-07 16:16

import django.db.models.deletion
import sales.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_sale_is_split_payment_sale_payment_breakdown_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='sale',
            name='sales_etr_rec_e4057a_idx',
        ),
        migrations.RemoveField(
            model_name='salecounter',
            name='year',
        ),
        migrations.AddField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Customer who made this purchase (for loyalty points)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='sales.customer'),
        ),
        migrations.AddField(
            model_name='sale',
            name='points_earned',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), help_text='Points earned from this sale (1% of total)', max_digits=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='sequence_number',
            field=models.PositiveIntegerField(blank=True, editable=False, help_text='Sequential number shared with ETR receipt', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='salecounter',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='salecounter',
            name='last_used',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='etr_receipt_number',
            field=models.CharField(blank=True, help_text='ETR receipt number in format: 00001, 00002, etc. (same number as sale_id)', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_id',
            field=models.CharField(default=sales.models.generate_sale_id, editable=False, max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['sequence_number'], name='sales_sequenc_ec4e1b_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['sale_id'], name='sales_sale_id_5f536f_idx'),
        ),
        migrations.RemoveField(
            model_name='sale',
            name='etr_receipt_counter',
        ),
    ]
